### PR TITLE
Improve getSigner provider validation in transactions.ts

### PR DESCRIPTION
**Pull request by adiled**
**What**: Updating the elimination logic in `transactions.ts` in `getSigner` to be more inclusive and robust.

**Why**: For full compatibility with ethers and ethers-based libraries. Issue was raised in https://github.com/skalenetwork/admin-ui when initializing TokenManager classes with an ethers `JsonRpcProvider`, then raised further when passing an ethers `Web3Provider`. Likely cause is the use of `instanceof` as a provider check, where the provider is moving between libraries that are using various different versions of ethers.

**How**: With a lot of vetting. There's a good chance that the changes have only positive side effects.

**Checklist**:

-   [ ] Documentation (not needed)
-   [x] Tests (human tests within `admin-ui`)
-   [x] Ready to be merged

### CODE REVIEW

**Comment by dmytrotkk** [comment]
@adiled hey 👋 
thanks for your PR

can you please sign CLA using an instruction above, so I can merge your changes

**Comment by adiled** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by adiled** [comment]
recheck

**Comment by dmytrotkk** [comment]
@adiled can you please take a look on test pipeline: https://github.com/skalenetwork/ima-js/actions/runs/4305910737/jobs/7565531067?pr=53

**Comment by adiled** [comment]
> @adiled can you please take a look on test pipeline: https://github.com/skalenetwork/ima-js/actions/runs/4305910737/jobs/7565531067?pr=53

Updated with minimal changes, tested tsc locally.

**Review by dmytrotkk — APPROVED** [review]

**Pull request merged**
